# .github/workflows/rss-check.yml

name: RSS to Discord

on:
  schedule:
    # Se déclenche toutes les 15 minutes
    - cron: '*/30 * * * *'
  # Permet de le lancer manuellement depuis l'onglet Actions de GitHub
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install rss-parser discord.js

    - name: Run script to check feeds
      run: node main.js
      env:
        DISCORD_WEBHOOKS: ${{ secrets.DISCORD_WEBHOOKS }}

    - name: Commit updated last_posts.json
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'chore: Update last posts from RSS feeds'
        file_pattern: 'last_posts.json'
        commit_user_name: 'GitHub Actions Bot'
        commit_user_email: 'actions@github.com'
